### ISSUE TITLE
残りタスク

### ISSUE THREAD

**Issue by mitsuharu** [yumemi-inc/daigirin-2024-2#21]
## 表紙

- [x] 本文のページ数を確定して、デザイナーさんにつたえる（本文 144ページ + 表紙 4 ページ = 148 ページ）
- [x] 表示画像で電子版を作成する
- [x] psdで印刷所に入稿する

## 目次

- [x] 脱稿された記事を目次に追加する
- [x] 表示順番をざっくりジャンルでソートする 
- [x] fix #17

## はじめに

- [x] 前回の内容に更新した（外部執筆者を除いた）

## 本文（10/7時点）

- [x] loveeさん （仮ページ追加済み）
- [x] うーたんさん（仮ページ追加済み）
- [x] 川島さん
- [x] 菅原さん

## 著者紹介

- [x] 表示順番を目次に揃える
- [x] タイトル未定を埋める

## 奥つけ

- [x] 初版の日など、誤りがないか確認する

**Comment by ykws** [comment]
最終チェック用

[ebook.pdf](https://github.com/user-attachments/files/17352682/ebook.pdf)

**Comment by ykws** [comment]
一通り目を通して以下の2つの修正 PR を作成しました

- #32 
- #33

**Comment by ykws** [comment]
@mitsuharu 入稿済みなので閉じて良いでしょうか？
